"""Generate TEMPORAL.md output from compute_modifiers() result."""

from __future__ import annotations

from pathlib import Path

from clawclaw_soul.prompt import modifiers_to_prompt


def generate_temporal_md(result: dict) -> str:
    """Generate TEMPORAL.md content from compute_modifiers() output.

    Args:
        result: Output dict from compute_modifiers()

    Returns:
        Markdown string for TEMPORAL.md
    """
    modifiers = result["modifiers"]
    prompt_block = modifiers_to_prompt(modifiers)

    lines = [
        "# TEMPORAL.md",
        "",
        f"<!-- Generated by agent-soul | agent: {result['agent_id']} -->",
        f"<!-- Computed: {result['computed_at']} | Phase: {result['phase']} -->",
        f"<!-- Next refresh: {result['next_refresh']} -->",
        "",
    ]

    if prompt_block:
        lines.append(prompt_block)
    else:
        lines.append("<!-- All modifiers neutral — no personality adjustments active -->")
        lines.append("")

    # Modifier summary table
    lines.append("## Current State")
    lines.append("")
    lines.append("| Modifier | Value | Direction |")
    lines.append("|----------|-------|-----------|")

    for name, value in modifiers.items():
        if value > 0.15:
            direction = "+" * min(3, int(value / 0.28) + 1)
        elif value < -0.15:
            direction = "-" * min(3, int(abs(value) / 0.28) + 1)
        else:
            direction = "~"
        lines.append(f"| {name} | {value:+.3f} | {direction} |")

    lines.append("")
    lines.append(f"Volatility: {result['volatility']:.2f} | Phase: {result['phase']}")
    lines.append(f"Strict mode: {'on' if result['strict_mode'] else 'off'}")
    lines.append("")

    return "\n".join(lines)


def write_temporal_md(
    result: dict,
    output_path: str | Path | None = None,
) -> Path:
    """Write TEMPORAL.md to disk.

    Args:
        result: Output dict from compute_modifiers()
        output_path: Where to write. Defaults to ~/clawd/TEMPORAL.md

    Returns:
        Path to written file
    """
    if output_path is None:
        output_path = Path.home() / "clawd" / "TEMPORAL.md"
    else:
        output_path = Path(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = generate_temporal_md(result)
    output_path.write_text(content, encoding="utf-8")

    return output_path
